language: php
php:
  - 5.6
sudo: required
dist: trusty

before_install:
  - sudo apt-get update
  - sudo apt-get install ruby-sass

install:
  - bin/install.sh

before_script:
  - npm install -g jslint

script:
  - jslint js/*.js
  - bin/travis-ci.sh
